apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mcp-bancolombia
  title: Bancolombia MCP Server
  description: |
    Servidor MCP (Model Context Protocol) reactivo basado en Java y Spring AI. 
    Proporciona herramientas de saludo, salud del sistema y acceso a información de usuarios.
    Implementa Clean Architecture y seguridad via API Key.

  tags:
    - mcp
    - ai
    - java
    - spring-boot
    - spring-ai
    - reactive
    - clean-architecture
    - bancolombia
  
  # Anotaciones para detección y configuración
  annotations:
    # URL del servidor MCP en PRODUCCIÓN
    server-url: 'http://localhost:8080/mcp/stream'
    
    # URLs adicionales por ambiente
    server-url-dev: 'http://localhost:8080/mcp/stream'
    server-url-qa: 'http://localhost:8080/mcp/stream'
    
    # Proyecto de Azure DevOps
    dev.azure.com/project: 'b267af7c-3233-4ad1-97b3-91083943100d'
    dev.azure.com/project-repo: 'NU1041001_Mcp_Server_MR'
    
    # Pipeline de build
    dev.azure.com/build-definition: '55727'
    
    # Ubicación del código fuente en el repositorio
    backstage.io/source-location: 'url:https://dev.azure.com/grupobancolombia/b267af7c-3233-4ad1-97b3-91083943100d/_git/NU1041001_Mcp_Server_MR?path=/demo_mcp_server'
    
    # TechDocs
    backstage.io/techdocs-ref: dir:.
    
    # Tipo de servidor MCP y protocolo
    mcp.io/protocol-version: '2024-11-05'
    mcp.io/server-type: 'stateless-http'
    
    # Información de arquitectura
    architecture.bancolombia.com/pattern: 'clean-architecture'
    architecture.bancolombia.com/language: 'java'
    architecture.bancolombia.com/framework: 'spring-ai-mcp'

  # Links
  links:
    - url: 'https://github.com/kenyodarz/Mcp-Java-Example'
      title: 'Código Fuente'
      icon: 'code'

    - url: 'http://localhost:8080/_build?definitionId=55727'
      title: 'Azure Pipeline'
      icon: 'build'

    - url: 'http://localhost:8080/mcp/stream'
      title: 'Endpoint MCP (Producción)'
      icon: 'cloud'

    - url: 'https://modelcontextprotocol.io/docs'
      title: 'Documentación MCP Protocol'
      icon: 'docs'

spec:
  type: mcp
  lifecycle: production
  owner: group:default/practicas-ingenieria-software
  system: inteligencia-artificial
  
  # APIs que proporciona (MCP Tools/Resources/Prompts)
  providesApis:
    - mcp-bancolombia-api

---
# Definición del API MCP proporcionada
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: mcp-bancolombia-api
  title: Bancolombia MCP API
  description: API del protocolo MCP que expone herramientas, recursos y prompts
  tags:
    - mcp
    - api
    - java
  
  annotations:
    server-url: 'https://inteligenciaartificial-int.apps.bancolombia.com/vsti-mcp/mcp'

spec:
  type: mcp
  lifecycle: production
  owner: group:default/practicas-ingenieria-software
  system: inteligencia-artificial
  
  # Definición de capacidades disponibles
  definition: |
    # Bancolombia MCP Capabilities
    
    ## Tools
    
    ### 1. saludoTool
    **Descripción**: Genera un saludo personalizado reactivo para el usuario.
    **Parámetros**:
    - `name` (string, requerido): Nombre de la persona a saludar.
    
    ### 2. healthCheck
    **Descripción**: Verifica el estado del servidor MCP. Retorna 'OK' si todo funciona correctamente.
    
    ---
    
    ## Resources
    
    ### 1. system-info
    **URI**: `resource://system/info`
    **Descripción**: Proporciona información básica del sistema y metadata del servidor MCP.
    
    ### 2. user-info
    **URI**: `resource://users/{userId}`
    **Descripción**: Obtiene información detallada de un usuario por su ID.
    
    ---
    
    ## Prompts
    
    ### 1. saludo
    **Descripción**: Genera un prompt de saludo personalizable.
    **Argumentos**:
    - `nombre` (string, requerido): Nombre de la persona a saludar.
    
    ### 2. bienvenida
    **Descripción**: Genera un prompt de bienvenida formal con título opcional.
    **Argumentos**:
    - `titulo` (string, opcional): Título o nombre para la bienvenida.
    
    ---
    
    ## Protocolo
    - **Host**: Spring Boot / Spring AI
    - **Transport**: SSE over HTTP
    - **Endpoint**: /mcp/stream
