apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mcp-bancolombia
  title: Bancolombia MCP Server
  description: |
    El MCP de Bancolombia (Java) cuenta con herramientas y recursos que permiten interactuar con el servidor 
    para obtener información del sistema, saludos personalizados y datos de usuario, utilizando la 
    potencia de Spring AI y Clean Architecture.

  tags:
    - mcp
    - ai
    - clean-architecture
    - github
    - java
    - spring-ai
    - devops

  annotations:
    # ============================================
    # GitHub Annotations (CRÍTICAS para TechDocs)
    # ============================================
    github.com/project-slug: 'kenyodarz/Mcp-Java-Example'
    backstage.io/source-location: 'url:https://github.com/kenyodarz/Mcp-Java-Example'

    # Build type - indica que usa GitHub Actions
    kaizen.bancolombia.com/build-type: 'githubactions'

    # ============================================
    # TechDocs Configuration
    # ============================================
    backstage.io/techdocs-ref: dir:.

    # ============================================
    # MCP Server URLs (Ambientes)
    # ============================================
    server-url: 'http://localhost:8080/mcp/stream'
    server-url-dev: 'http://localhost:8080/mcp/stream'
    server-url-qa: 'http://localhost:8080/mcp/stream'

    # ============================================
    # MCP Protocol Specifications
    # ============================================
    mcp.io/protocol-version: '2025-06-18'
    mcp.io/server-type: 'streamable-http'

    # ============================================
    # Architecture Metadata
    # ============================================
    architecture.bancolombia.com/pattern: 'clean-architecture'
    architecture.bancolombia.com/language: 'java'
    architecture.bancolombia.com/framework: 'spring-ai-mcp'

  links:
    - url: 'https://github.com/kenyodarz/Mcp-Java-Example'
      title: 'Código Fuente (GitHub)'
      icon: 'github'

    - url: 'https://github.com/kenyodarz/Mcp-Java-Example/actions'
      title: 'GitHub Actions'
      icon: 'build'

    - url: 'http://localhost:8080/mcp/stream'
      title: 'Endpoint MCP (Local)'
      icon: 'cloud'

    - url: 'https://modelcontextprotocol.io/docs'
      title: 'Documentación MCP Protocol'
      icon: 'docs'

spec:
  type: mcp
  lifecycle: production
  owner: group:default/exodia
  system: inteligencia-artificial
  subcomponentOf: component:default/mcp-servers-monorepo

  providesApis:
    - mcp-bancolombia-api

---

apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: mcp-bancolombia-api
  title: Bancolombia MCP API
  description: API MCP que expone las herramientas, recursos y prompts del servidor Java reactivo.

  tags:
    - mcp
    - api

  annotations:
    server-url: 'http://localhost:8080/mcp/stream'
    github.com/project-slug: 'kenyodarz/Mcp-Java-Example'

spec:
  type: mcp
  lifecycle: production
  owner: group:default/exodia
  system: inteligencia-artificial

  definition: |
    # Bancolombia MCP Tools

    ## Available Tools
    
    ### 1. saludoTool
    **Descripción**: Genera un saludo personalizado reactivo para el usuario.
    
    **Parámetros**
    - `name` (string requerido): Nombre de la persona a saludar.
    
    **Retorna**
    - `greeting` (string): Mensaje de saludo personalizado de bienvenida al servidor MCP de Bancolombia.
    
    ---
    
    ### 2. healthCheck
    **Descripción**: Verifica el estado del servidor MCP.
    
    **Retorna**
    - `status` (string): 'OK' si el servidor está funcionando correctamente y los componentes reactivos están activos.
    
    ---
    
    ## Resources
    
    ### 1. system-info
    **Descripción**: Proporciona información básica del sistema y metadata del servidor MCP (versión, estado, capacidades).
    **URI**: `resource://system/info`
    
    ### 2. user-info
    **Descripción**: Obtiene información detallada de un usuario por su ID desde la API de Simpsons.
    **URI**: `resource://users/{userId}`
    
    ---
    
    ## Prompts
    
    ### 1. saludo
    **Descripción**: Genera un prompt de saludo personalizable.
    **Argumentos**:
    - `nombre` (string requerido): Nombre de la persona a saludar.
    
    ### 2. bienvenida
    **Descripción**: Genera un prompt de bienvenida formal con título opcional.
    **Argumentos**:
    - `titulo` (string opcional): Título o nombre para la bienvenida.

    ## Protocolo
    - **Versión**: MCP 2025-06-18
    - **Formato**: JSON-RPC 2.0
    - **Transport**: SSE (Server-Sent Events) over HTTP
    - **Content-Type**: application/json
    - **Accept**: text/event-stream, application/json
    - **Endpoint**: /mcp/stream
